project:
  type: website
  output-dir: docs

website:
  title: "AI4SG"
  favicon: images/logo.jpeg
  navbar:
    logo: images/logo.jpeg
    right:
      - href: index.qmd
        text: Home
      - href: seminar.qmd
        text: Seminar Series
      - href: grading.qmd
        text: Grading Policy
      - href: faq.qmd
        text: FAQs
      - href: schedule.qmd
        text: Lectures 
      - href: tentative.qmd
        text: Tentative deadlines
      - href: https://nipunbatra.github.io
        text: Instructor Homepage


format:
  html:
    theme:
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto

